version: '3.2'
services:
  postgres:
    image: postgres:11-alpine
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=example
    volumes:
      - "/var/lib/postgresql/data"
    ports:
      - "5433:5432"
    expose:
      - "5432"